:concurrency: 3
:queues:
  - default
  - webhooks

:scheduler:
  :schedule:
    met_art_refresh:
      every: '1h'
      class: MetArtRefreshJob
      queue: default
    interview_alert_check:
      every: '15m'
      class: InterviewAlertCheckJob
      queue: default
